### ISSUE TITLE
Serial UART not working

### ISSUE THREAD

**Issue by ouranos6** [robertsLando/node-red-contrib-m-bus#10]
Hi, 

Hardware:
Rpi 3
USB to m-bus
TTL to m-bus
TSS721 Module M-BUS To TTL with RX TX Indicator STM32 Development Board Free Shipping
https://a.aliexpress.com/_A7ii0r

I have two setups, the first one with an USB m-bus who is working very well. 

The second one is an ttl m-bus and I have an issue when I set ‘/dev/ttyAMA0’, the server loose connection 

If I use the serial IN I have no problem to connect. 

What I’am doing wrong?

**Comment by ouranos6** [comment]
Ok now I have someting else, after disabling the console to serial and enabling the serial port I have another strange behaviour.

each 10 sec. it try to reconnect and say "one device loaded from file" I guess it's before I've tried with the USB to m-bus

![image](https://user-images.githubusercontent.com/20718760/97109393-45ce7180-16d3-11eb-8f39-9c4ffd80b22a.png)

![image](https://user-images.githubusercontent.com/20718760/97109405-567ee780-16d3-11eb-9c54-b34707b8fcc1.png)

Any clue?

**Comment by robertsLando** [comment]
Try to delete the file

**Comment by ouranos6** [comment]
ok but where is the file?
`return RED.settings.userDir + '/' + DEVICES_FILE + (node.name ? '_' + node.name : '') + '.json';`
but in .node-red/ I can't see anyting with devices... .json

**Comment by robertsLando** [comment]
You should check what's your settings userDir. You find it in settings.json. By default it should be: `~/.node-red`

**Comment by ouranos6** [comment]
ok found it and remove it, reboot the RPI and now it  says `error: no device to update`

**Comment by ouranos6** [comment]
after a new reboot and a new scan I have `scan complete 0 devices found` but it's wired on the same way that I was using the USB

**Comment by robertsLando** [comment]
I cannot see anything wrong here, unfortunally sometimes the problems could be caused by wrong connections or usb adapters that are not working properly

**Comment by ouranos6** [comment]
ok, I will try again tonight, and let you know if it's working right

**Comment by tsr8** [comment]
Similar issue. `scan complete 0 devices found`. I have M-BUS to RS485 converter, if I connect it to PC and using MBus scan software (M-Bus sheet) then all connected heat meters founded (11) but in node-red it is zero. Can't get device data from `getDevice`: Error while reading device 67102948 : Error: Failed to send/receive M-Bus request frame[67102948], where 67102948 is the secondary address. 
What could be wrong? 
Is libmbus neccessary to node-red-contrib-m-bus work?

**Comment by tsr8** [comment]
I have solved my issue. It was caused by too small timeouts in libmbus library. Created an libmbus issue: https://github.com/rscada/libmbus/issues/186
And node-mbus issue: https://github.com/Apollon77/node-mbus/issues/70
