### ISSUE TITLE
Missing node-types

### ISSUE THREAD

**Issue by oygr** [robertsLando/node-red-contrib-m-bus#12]
Hi
My flow has missing node-types after install. Do you have an easy solution on that?

Regards
/Øyvind
[
<img width="709" alt="Skjermbilde 2021-01-01 kl  12 18 53" src="https://user-images.githubusercontent.com/45861369/103437779-028d0380-4c2c-11eb-9343-1a54323fce98.png">
](url)

**Comment by robertsLando** [comment]
You have to install node red dashboard nodes

**Comment by oygr** [comment]
Thanks.
