### ISSUE TITLE
UDEV symlinks with /dev/ttyUSBx interfaces not working

### ISSUE THREAD

**Issue by Webbeh** [robertsLando/node-red-contrib-m-bus#17]
Hi there.

We use mini computers with node-red, and some of them have serial devices in them, while others don't.

We created a UDEV rule to always have our USB<->Serial MBUS interface have the same path (/dev/tty_mbus) but it seems this node doesn't support symlinks to the interface.

Is it possible to check/implement ?

Thank you !

**Comment by robertsLando** [comment]
The underlyinng library used is node-mbus, if the path provided isn't working the problem is there

**Comment by Webbeh** [comment]
I think I figured out the issue. I was symlinking the /dev/bus/... (by having udev listen to subsystem USB rather than TTY).

Symlinking the TTY device properly seems to work. Sorry for bothering you!

**Comment by robertsLando** [comment]
No worries happy you fixed it :)
