### ISSUE TITLE
Could not locate bindings file

### ISSUE THREAD

**Issue by demetz** [robertsLando/node-red-contrib-m-bus#2]
Hi,

after installing your package, I receive the following error message:

Error: Could not locate the bindings file. Tried:
 → /home/deploy/.node-red/node_modules/node-red-contrib-m-bus/node_modules/node-mbus/build/mbus.node
 → /home/deploy/.node-red/node_modules/node-red-contrib-m-bus/node_modules/node-mbus/build/Debug/mbus.node
 → /home/deploy/.node-red/node_modules/node-red-contrib-m-bus/node_modules/node-mbus/build/Release/mbus.node
 → /home/deploy/.node-red/node_modules/node-red-contrib-m-bus/node_modules/node-mbus/out/Debug/mbus.node
 → /home/deploy/.node-red/node_modules/node-red-contrib-m-bus/node_modules/node-mbus/Debug/mbus.node
 → /home/deploy/.node-red/node_modules/node-red-contrib-m-bus/node_modules/node-mbus/out/Release/mbus.node
 → /home/deploy/.node-red/node_modules/node-red-contrib-m-bus/node_modules/node-mbus/Release/mbus.node
 → /home/deploy/.node-red/node_modules/node-red-contrib-m-bus/node_modules/node-mbus/build/default/mbus.node
 → /home/deploy/.node-red/node_modules/node-red-contrib-m-bus/node_modules/node-mbus/compiled/8.10.0/linux/arm/mbus.node

node.js: v8.10.0
node-red: v0.19.1
node-red-contrib-m-bus: v1.3.0

Any idea what might be going wrong? I am currently using libmbus directly without a problem on the same machine.

Best,

Dennis

**Comment by robertsLando** [comment]
@demetz Try to run the command `npm rebuild` in ~/.node-red directory. It seems not an error related with the node itself but with npm.

If you get any error try to remove the package and reinstall it: 

`npm uninstall node-red-contrib-m-bus --save`

`npm install node-red-contrib-m-bus --save`

Let me know if you fix it.

**Comment by demetz** [comment]
thanks.

Reinstalling over the command-line solved the problem...
