### ISSUE TITLE
Install Error error make: *** [mbus.target.mk:118: Release/obj.target/mbus/src/main.o] Error 127

### ISSUE THREAD

**Issue by sofa74surfer** [robertsLando/node-red-contrib-m-bus#28]
I tried to install node-red-contrib-m-bus and using Home Assistant OS. After some other issues like missing python3, gcc, make and musl-dev, I'm now on this point here: 

119 verbose stack Error: command failed
119 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
119 verbose stack     at ChildProcess.emit (node:events:513:28)
119 verbose stack     at maybeClose (node:internal/child_process:1091:16)
119 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
120 verbose pkgid node-mbus@1.2.2
121 verbose cwd /config/node-red
122 verbose Linux 5.15.90
123 verbose node v18.9.1
124 verbose npm  v8.10.0
125 error code 1
126 error path /config/node-red/node_modules/node-mbus
127 error command failed
128 error command sh -c node-gyp rebuild
129 error make: Entering directory '/config/node-red/node_modules/node-mbus/build'
129 error   CC(target) Release/obj.target/libmbus/libmbus/mbus/mbus-protocol-aux.o
129 error   CC(target) Release/obj.target/libmbus/libmbus/mbus/mbus-protocol.o
129 error   CC(target) Release/obj.target/libmbus/libmbus/mbus/mbus-serial.o
129 error   CC(target) Release/obj.target/libmbus/libmbus/mbus/mbus-tcp.o
129 error   CC(target) Release/obj.target/libmbus/libmbus/mbus/mbus.o
129 error   AR(target) Release/obj.target/mbus.a
129 error   COPY Release/mbus.a
129 error   CXX(target) Release/obj.target/mbus/src/main.o
129 error make: Leaving directory '/config/node-red/node_modules/node-mbus/build'
130 error gyp info it worked if it ends with ok
130 error gyp info using node-gyp@9.0.0
130 error gyp info using node@18.9.1 | linux | x64
130 error gyp info find Python using Python version 3.10.10 found at "/usr/bin/python3"
130 error gyp info spawn /usr/bin/python3
130 error gyp info spawn args [
130 error gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
130 error gyp info spawn args   'binding.gyp',
130 error gyp info spawn args   '-f',
130 error gyp info spawn args   'make',
130 error gyp info spawn args   '-I',
130 error gyp info spawn args   '/config/node-red/node_modules/node-mbus/build/config.gypi',
130 error gyp info spawn args   '-I',
130 error gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
130 error gyp info spawn args   '-I',
130 error gyp info spawn args   '/root/.cache/node-gyp/18.9.1/include/node/common.gypi',
130 error gyp info spawn args   '-Dlibrary=shared_library',
130 error gyp info spawn args   '-Dvisibility=default',
130 error gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.9.1',
130 error gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
130 error gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.9.1/<(target_arch)/node.lib',
130 error gyp info spawn args   '-Dmodule_root_dir=/config/node-red/node_modules/node-mbus',
130 error gyp info spawn args   '-Dnode_engine=v8',
130 error gyp info spawn args   '--depth=.',
130 error gyp info spawn args   '--no-parallel',
130 error gyp info spawn args   '--generator-output',
130 error gyp info spawn args   'build',
130 error gyp info spawn args   '-Goutput_dir=.'
130 error gyp info spawn args ]
130 error gyp info spawn make
130 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
130 error make: g++: No such file or directory
130 error make: *** [mbus.target.mk:118: Release/obj.target/mbus/src/main.o] Error 127
130 error gyp ERR! build error 
130 error gyp ERR! stack Error: `make` failed with exit code: 2
130 error gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
130 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
130 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
130 error gyp ERR! System Linux 5.15.90
130 error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
130 error gyp ERR! cwd /config/node-red/node_modules/node-mbus
130 error gyp ERR! node -v v18.9.1
130 error gyp ERR! node-gyp -v v9.0.0
130 error gyp ERR! not ok
131 verbose exit 1
132 timing npm Completed in 8513ms
133 verbose unfinished npm timer reify 1676817092901
134 verbose unfinished npm timer reify:build 1676817094287
135 verbose unfinished npm timer build 1676817094289
136 verbose unfinished npm timer build:deps 1676817094289
137 verbose unfinished npm timer build:run:install 1676817094296
138 verbose unfinished npm timer build:run:install:node_modules/node-mbus 1676817094297
139 verbose code 1
140 error A complete log of this run can be found in:
140 error     /root/.npm/_logs/2023-02-19T14_31_32_547Z-debug-0.log

Do you have any hint, whats going wrong here?

**Comment by robertsLando** [comment]
@sofa74surfer Did you installed 

```
sudo apt install build-essential  
```

?

**Comment by sofa74surfer** [comment]
Great, thank you. There is no build-essential and apt for alpine-linux (Home Assistant OS), but with your hint I found out, the moste suitable package is build-base. After "apk add build-base" on HA OS, it worked.

**Comment by robertsLando** [comment]
@sofa74surfer Glad it worked for you 🙏🏼
