### ISSUE TITLE
[Feature] Parse M-Bus data node

### ISSUE THREAD

**Issue by petrkr** [robertsLando/node-red-contrib-m-bus#30]
Is possible in some easy way create node which will only parse M-Bus payload?

Use case:
 I have ESP32 with implemented M-Bus command to read device. Response i M-Bus frame. This frame I want to send to NodeRED (over MQTT) and there I want parse it.

I can do simple TCP -- UART Bridge with ESP32 too, which will probably work. But I do not have public IP on ESP32 so NodeRED instance can not contact this device. So I can not use either Serial nor TCP client node.

**Comment by robertsLando** [comment]
@petrkr Nope, I'm sorry
