### ISSUE TITLE
Missing dependent node red library.

### ISSUE THREAD

**Issue by chalupp** [robertsLando/node-red-contrib-m-bus#35]
Hi,

I am using Node Red 3.0.2 under Docker.
The M-Bus nodes appeared properly after the import, but there is still missing library of nodes.
Can you help me where can I find it?
It is not mentioned in description.

Thanx a lot.

Kind regards

Peter
<img width="1017" alt="Noddered" src="https://github.com/robertsLando/node-red-contrib-m-bus/assets/50446050/c6f8ae31-ef56-4754-99a0-6cf0a5d81b7d">
<img width="1044" alt="Snímka obrazovky 2023-06-12 070118" src="https://github.com/robertsLando/node-red-contrib-m-bus/assets/50446050/2919e746-b9b5-46a8-b3ac-8b6d17638272">

**Comment by robertsLando** [comment]
you also need to install  `node-red-dashboard`

**Comment by chalupp** [comment]
Thanx :-)
