### ISSUE TITLE
IPv6 is not working

### ISSUE THREAD

**Issue by petrkr** [robertsLando/node-red-contrib-m-bus#36]
If trying to connect on IPv6 only M-Bus host, it says can not connect.

Tried
 - IPv6
 - [IPv6]
 - Hostname

```
20 Jun 15:05:01 - [info] [mbus-client:Test] Connection closed
20 Jun 15:05:01 - [error] [mbus-client:Test] Error while connecting No connection possible to MBus Host itron:1234
```

Here you can see port is part of IP, but it could be only due logging format
```
20 Jun 15:05:18 - [info] [mbus-client:Test] Connection closed
20 Jun 15:05:18 - [error] [mbus-client:Test] Error while connecting No connection possible to MBus Host 2a00:abcd:4018:e490:860d:8eff:fec2:abcd:1234
```

```
20 Jun 15:05:18 - [info] [mbus-client:Test] Connection closed
20 Jun 15:05:18 - [error] [mbus-client:Test] Error while connecting No connection possible to MBus Host [2a00:abcd:4018:e490:860d:8eff:fec2:abcd]:1234
```

**Comment by petrkr** [comment]
After investigation, this is part of those issues

(Root cause here) https://github.com/rscada/libmbus/issues/209
(Project which use libmbus) https://github.com/Apollon77/node-mbus/issues/120

**Comment by robertsLando** [comment]
@petrkr Thanks for the reference, let me know if/when the bug is solved on main lib so I can bump it here to and make a new release 🙌🏼

**Comment by petrkr** [comment]
After update to latest version 3.1.1 IPv6 already works.

Regards

![image](https://github.com/robertsLando/node-red-contrib-m-bus/assets/6428351/5e7fc834-38d3-45d3-8f72-af3c4acf6b53)
