### ISSUE TITLE
Mbus-KNX node red-izar center

### ISSUE THREAD

**Issue by abbasaabbas** [robertsLando/node-red-contrib-m-bus#4]
Hi, 

Further to my mail, I have several mbus counters or slaves (Sharky 755) connected to a mbus-usb gateway (IZAR Center-dhiel). I found your flow and I tried it to get all measurements.

For now, I am using their dedicated software to get all measurments. I attached an image of the log output.
  
Thanks for your help.

Abbas
![IZAR](https://user-images.githubusercontent.com/38360398/60076398-bd7b3d80-9727-11e9-9390-2b380c797913.PNG)

**Comment by robertsLando** [comment]
Could you try to install latest version 1.3.1 and send me the log output if you see any error? So:

cd ~/.node-red
npm install —save node-red-contrib-m-bus —unsafe-perm

Daniel

**Comment by robertsLando** [comment]
Hi @abbasaabbas, 

could you try to install latest version 1.3.1 and send me the log output if you see any error? So:

```bash
cd ~/.node-red
npm install —save node-red-contrib-m-bus —unsafe-perm
```

**Comment by abbasaabbas** [comment]
I used your command: npm install --save node-red-contrib-m-bus --unsafe-perm
I got :
> node-mbus@1.0.0 install /home/pi/.node-red/node_modules/node-mbus
> node-gyp rebuild

make : on entre dans le répertoire « /home/pi/.node-red/node_modules/node-mbus/build »
  CC(target) Release/obj.target/libmbus/libmbus/mbus/mbus-protocol-aux.o
  CC(target) Release/obj.target/libmbus/libmbus/mbus/mbus-protocol.o
  CC(target) Release/obj.target/libmbus/libmbus/mbus/mbus-serial.o
  CC(target) Release/obj.target/libmbus/libmbus/mbus/mbus-tcp.o
  CC(target) Release/obj.target/libmbus/libmbus/mbus/mbus.o
  AR(target) Release/obj.target/mbus.a
  COPY Release/mbus.a
  CXX(target) Release/obj.target/mbus/src/main.o
  CXX(target) Release/obj.target/mbus/src/mbus-master.o
  CXX(target) Release/obj.target/mbus/src/util.o
  SOLINK_MODULE(target) Release/obj.target/mbus.node
  COPY Release/mbus.node
make : on quitte le répertoire « /home/pi/.node-red/node_modules/node-mbus/build »
+ node-red-contrib-m-bus@1.3.1
added 3 packages from 8 contributors, updated 3 packages and audited 1958 packages in 114.761s
found 0 vulnerabilities

**Comment by abbasaabbas** [comment]
It's works but I get only the gateway, not the counters.

![mbus](https://user-images.githubusercontent.com/38360398/60079023-6bd5b180-972d-11e9-8067-cb032acfc0f2.PNG)

**Comment by robertsLando** [comment]
A gateway? I don’t understand, what is your network structure? Aren’t the m-bus devices directly connected to your m-bus usb/tcp converter? 

Daniel

**Comment by robertsLando** [comment]
Try to read them by primary ids if you have addressed them, id you haven’t addressed them you need to do it, also add here some log output

Daniel

**Comment by abbasaabbas** [comment]
I get this msg : Error while connecting No connection possible to MBus Host "IP":10001

**Comment by robertsLando** [comment]
The node works properly, it is more likely a comfiguration issue with your device

Daniel
