### ISSUE TITLE
M-Bus Controller node don't pass msg values

### ISSUE THREAD

**Issue by SindreLindahl** [robertsLando/node-red-contrib-m-bus#43]
M-Bus Controller nodes accepts topic, then outputs topic and payload. But it also discards all other message variables. These are some times important to keep with the message and cumbersome to transfer around in a side flow.

Any way to have this node pass variables to output?

**Comment by robertsLando** [comment]
@SindreLindahl Want to submit a PR to fix that?

**Comment by SindreLindahl** [comment]
Done: https://github.com/robertsLando/node-red-contrib-m-bus/pull/44
