### ISSUE TITLE
not reading all datastore values from some meters?

### ISSUE THREAD

**Issue by beireken** [robertsLando/node-red-contrib-m-bus#5]
I'm trying to read an eastron sdm630 Mbus energy meter with the nodered node.
It works but i seem to be missing a lot of values.
In the manual here you see the values under heading 5.3, those are the one's i can read.
The value's under heading 6.2 (voltage etc.) are not available in the datastore received.

https://bg-etech.de/download/manual/SDM630-Mbus-protocol.pdf

Can i work around this using the node?
Thank you for any help!

**Comment by robertsLando** [comment]
I can’t do anything for the values that are not listed, I get them using node mbus wrapper 

Daniel

**Comment by beireken** [comment]
Ok, I'll ask the question at node-mbus then.
Thank you!
