### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by Fortuide** [robertsLando/node-red-contrib-m-bus#7]
![Bez tytułu](https://user-images.githubusercontent.com/57669504/68674721-bb8b0d00-0556-11ea-896c-76635d42b7e2.png)
I'm having some trouble opening the conntection to my converter. I have a USB to RS232 which then connects to Techbase RS232/Mbus however whatever i set in the client node i get this error and constant "Reconnecting" status. Have i missed something to configure?

**Comment by robertsLando** [comment]
Check permissions on tty. Add user to the group dialout and also try to run “sudo chown 777 /dev/ttyUSB0” (change USB0) with your tty name if different)

Daniel

**Comment by Fortuide** [comment]
I was about to add that I'm not operating on Linux but on Windows 10, I had set the serialport to COM10 (which i know is the port that the converter is connected to from other Mbus software) in client node but it returns error shown above

**Comment by robertsLando** [comment]
What is the exact value you set in serial field? 

Daniel

**Comment by Fortuide** [comment]
"COM10". I tried both writing it in and choosing from the list of connected ports

**Comment by robertsLando** [comment]
Sorry, I don’t know how to fix this

Daniel
